DROP TABLE IF EXISTS OBJ_ROOM_HIS;
DROP TABLE IF EXISTS ROOM_INFO;
DROP TABLE IF EXISTS FIRE_JUDGE_RESULT;
DROP TABLE IF EXISTS INDRECT_FIRE_PLAN;
DROP TABLE IF EXISTS COMMAND_INFO;

CREATE TABLE ROOM_INFO (
    id BIGINT PRIMARY KEY,
    title VARCHAR(255),
    totalTime INT,
    startTime TIMESTAMP
);

CREATE TABLE FIRE_JUDGE_RESULT (
    ID BIGINT,
    ROOM_ID VARCHAR(100),
    OBJ_ID INT NOT NULL,
    TAR_OBJ_ID INT NOT NULL,
    PHYSICAL_TIME INT,
    SIM_TIME INT NOT NULL,
    PRIMARY KEY (OBJ_ID, TAR_OBJ_ID, SIM_TIME)
);

CREATE TABLE INDRECT_FIRE_PLAN (
    ID INT,
    ROOM_ID INT,
    OBJ_ID INT,
    CREATE_TIME TIMESTAMP,
    IF_ID INT NOT NULL,
    SIM_TIME INT NOT NULL,
    PRIMARY KEY (IF_ID, SIM_TIME)
);

CREATE TABLE COMMAND_INFO (
    ID INT,
    ROOM_ID INT,
    OBJ_ID INT NOT NULL,
    RECEIVE_TIME TIMESTAMP,
    SIM_TIME INT NOT NULL,
    PRIMARY KEY (OBJ_ID, SIM_TIME)
);

CREATE TABLE OBJ_ROOM_HIS (
    ROOM_OBJECT_ID INT NOT NULL,
    SCENARIO_ID INT,
    ROOM_ID INT,
    ORG_SEQ VARCHAR(100),
    OBJ_CODE VARCHAR(20),
    OBJ_VEHICLE_NUM INT,
    OBJ_LEVEL INT,
    OBJ_PROTO_ID INT,
    SIDE VARCHAR(20),
    OBJ_NAME VARCHAR(200),
    ICON_3D VARCHAR(255),
    ICON_2D VARCHAR(255),
    ICON_SIZE INT,
    OBJ_TYPE INT,
    COMBAT_GROUP VARCHAR(200),
    STEALTH_VALUE INT,
    TARGET_VALUE INT,
    WORK_OBSTACLE INT,
    ENTRY_TIME INT,
    PERSON_COUNT INT,
    ARMOR_LEVEL INT,
    COMBAT_MODE INT,
    MOVING_FIRE_CAPABILITY INT,
    WEAPON_DIVERSITY INT DEFAULT 0,
    RECON_COMMS_TYPE INT,
    CARRYING_CAPACITY INT,
    MOVE_STOP_CONVERT_TIME INT,
    ATTACK_INTERVAL INT,
    OFF_ROAD_MAX_SPEED INT,
    NORMAL_ROAD_MAX_SPEED INT,
    FAST_ROAD_MAX_SPEED INT,
    HIGHWAY_MAX_SPEED INT,
    RECON_PERSONNEL INT,
    RECON_VEHICLE INT,
    RECON_AIR INT,
    RECON_OBSTACLE INT,
    RECON_MINEFIELD INT,
    DEPLOYMENT_DURATION INT,
    WITHDRAWAL_DURATION INT,
    CAMOUFLAGE_DURATION INT,
    NORMAL_AMMUNITION INT,
    HEAVY_AMMUNITION INT,
    MEDIUM_AMMUNITION INT,
    SMALL_AMMUNITION INT,
    AMMUNITION_CONSUMPTION INT,
    WEAPON_LIST INT,
    CARRYING_OBJ_LIST VARCHAR(500),
    OPERATOR_ID VARCHAR(500),
    OBJ_CURRENT_VEHICLE_NUM INT,
    OBJ_PARENT_ID INT,
    AI_INTERFACE INT,
    OBJ_SON_NUM VARCHAR(50),
    OBJ_SON_ORIGINAL_ID INT,
    CURRENT_POS INT,
    NEXT_POS INT,
    DIRECTION INT,
    CURRENT_SPEED INT,
    MOVING INT,
    STOPPING INT,
    SUPPRESSED INT DEFAULT 0,
    COOLING INT DEFAULT 0,
    IF_PLAN_ID INT DEFAULT 0,
    HIDE_STATUS INT DEFAULT 0,
    FIRING_OR_MARCHING INT DEFAULT 0,
    COMBAT_HEIGHT INT,
    WEAPON_ID INT,
    WEAPON_RANGE INT,
    WEAPON_NUM INT,
    FORT_OBJ_ID INT,
    SUPPORTING INT,
    LOAD_STATE INT,
    VISIBLE INT,
    SIM_TIME INT,
    CREATE_TIME BIGINT,
    IF_COUNTDOWN BIGINT,
    WEAPON_COUNTDOWN TIMESTAMP,
    TARGET_ID BIGINT NOT NULL,
    FIRST_CATEGORY_CODE INT,
    SECOND_CATEGORY_CODE INT,
    AIR_DEFENSE_RANGE VARCHAR(50),
    PRIMARY KEY (ROOM_OBJECT_ID, TARGET_ID)
);

CREATE INDEX IDX_OBJ_ROOM_HIS_SIM_TIME ON OBJ_ROOM_HIS(SIM_TIME);
CREATE INDEX IDX_OBJ_ROOM_HIS_TARGET_ID ON OBJ_ROOM_HIS(TARGET_ID);
